<?php
/**
 * Created by PhpStorm.
 * User: snark | itfrogs.ru
 * Date: 10/25/16
 * Time: 4:06 PM
 */

namespace vendors\Model\Orm;
use \RS\Orm\Type;

/**
* Объект - поставщик
*/
class Vendor extends \RS\Orm\OrmObject
{
    protected static
        $table = 'vendors_vendor';
        
    function _init()
    {
        parent::_init()->append(array(
            t('Основные'),
                'site_id' => new Type\CurrentSite(),
                'title' => new Type\Varchar(array(
                    'maxLength' => '50',
                    'description' => t('Название поставщика'),
                    'checker' => array('chkEmpty', t('Название поставщика - обязательное поле'))
                )),
        ));
    }

    /*
     * @param int $site_id - поддержка мультисайтовости
     * @returm mixed
     */
    public function getAllVendors($site_id = null) {
        $vendors = \RS\Orm\Request::make()->from($this);
        if ($site_id) {
            $vendors->where(array('site_id' => intval($site_id)));
        }
        return $vendors->objects();
    }

    public function getValues()
    {
        return parent::getValues(); // TODO: Change the autogenerated stub
    }
}

